# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Enable 2 status bars. Note that status bars are numbered 0 through n-1 from top to bottom.
set-option -g status 5

# Set background color to transparent
set -g status-style bg='#282828'

# Set active window to be highlighted
set -g window-status-current-style bg=grey,fg=white

# Get rid of default status-right info
set -g status-right ""

# Place working directory info on status line 1
set -g status-format[1] "#{pane_current_path}"

# Swap status lines 0 & 1 so a blank line pads the status bar
set -Fg 'status-format[2]' '#{status-format[0]}'
set -g status-format[0] "---tmux---"

# Configure status line 3 to show git info on the left
set -g status-format[3] "#[align=left]#(gitmux \"#{pane_current_path}\")"


# Open new panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "{#pane_current_path}"

# Set scroll speed
set -g @scroll-speed-num-lines-per-scroll 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'