#!/usr/bin/env bash
set -euo pipefail

BRANCH=${1:-darwin}  # Default to 'darwin' if no argument provided
DOTFILES_DIR=${1:-"$HOME/dotfiles/"}
# Ensure DOTFILES_DIR ends with a slash. This is necessary for rsync to work correctly.
SOURCE="${DOTFILES_DIR%/}/"
DESTINATION="$HOME/"

git checkout "$BRANCH"

rsync \
    --archive \
    --verbose \
    --exclude .git \
    --exclude .gitignore \
    --exclude .DS_Store \
    --exclude propagate_dotfiles \
    --exclude update_dotfiles \
    "$SOURCE" \
    "$DESTINATION"