github.com:
    user: anthnyalxndr
    git_protocol: https
    users:
        anthnyalxndr:
            oauth_token: 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
    oauth_token: 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
