#!/usr/bin/env bash

# Run `alias` to see active aliases.
# Run whence $alias to see the command an alias aligns to.

# "alert" alias for long running commands.  Usage: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias bashrc="code ~/.bashrc"
alias c="code"
alias e="echo"
alias fcmd="{compgen -c && alias | sed 's/\=.*//'} | fzf"
alias fman="fcmd | xargs man"
alias g="/usr/bin/git"
alias hfzf="history | cut -c 8- | fzf --tac"
alias la='ls -A'
alias lc="wc -l"         # ws with the `l` flag returns a line count
alias less="less --IGNORE-CASE"
alias line-count="wc -l" # ws with the `l` flag returns a line count
alias ll='ls -alF'
alias lower="tr \"[:upper:]\" \"[:lower:]\""
alias lsd="ls -lad */"
alias ltrim="sed -E 's/^[[:space:]]+//'"
alias profile="code ~/.profile"
alias rtrim="sed -E 's/[[:space:]]+$//'"
alias sudocode="code --user-data-dir=ROOT_VSCODE_DIR"
alias t="tmux"
alias tc="tmux command" # quick access to tmux command mode
alias tcm="tmux copy-mode"
alias tmux-conf='echo $XDG_CONFIG_HOME/tmux/tmux.conf'
alias tobin="bc --obase 2 --expression"
alias tohex="bc --obase 16 --expression"
alias trim="sed -E 's/^[[:space:]]+//' | sed -E 's/[[:space:]]+$//'"
alias update_dotfiles='$HOME/Projects/shell_scripts/update_dotfiles/update_dotfiles'
alias update-dotfiles=update_dotfiles
alias upper="tr \"[:lower:]\" \"[:upper:]\""
alias word-count=wc