#!/usr/bin/env bash

# OVERVIEW
# join_array takes a delimiter and several strings or an expanded
# array (${array[@]}) as arguments. From there it joins the strings or array
# elements together into a single string delimited by the delimiter and prints
# the new string to the console

function join_array {
    local delimiter=${1-} string=${2-}
    if shift 2; then
        printf %s "$string" "${@/#/$delimiter}"
    fi
}

# EXAMPLES
#   Join a set of strings together with a `,`
#     $ join_array , foo bar baz
#     foo, bar, baz
#
#   Join the elements of an array together with a `,`
#     $ arr=(1 2 3)
#     $ join_array , "${arr[@]}"
#     1, 2, 3
