# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Configure status bar time format
# See foragoodstrftime.com for help changing these values.
set -g status-right "%A, %m/%d/%Y %l:%M %p"

# # Set background color to transparent
set -g status-style bg=default

# # Set active window to be highlighted
set -g window-status-current-style bg=grey,fg=white

# Add github info to status bar
set -g status-right '#(gitmux "#{pane_current_path}")'

# Open new panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "{#pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g @scroll-speed-num-lines-per-scroll 1
